FROM docker.io/maven:3.6.3-jdk-11 AS builder

ENV PROFILE=prod

WORKDIR /opt/app

COPY . .

RUN mvn package

FROM docker.io/openjdk:11.0-jre

COPY --from=builder /opt/app/target/*.jar /app.jar

EXPOSE 8080

CMD java -jar /app.jar
